# Id HTML du conteneur
container_id:      ''

# Classe HTML du conteneur
container_class:  ''

# Contenu HTML affiché avant le fil d'Ariane 
before:           ''

# Contenu HTML affiché après le fil d'Ariane
after:            ''

# Mise en file automatique des scripts
enqueue_scripts:  true