# @var string|bool $content_display Affichage du contenu de la page
#   'before'|true : Affiche le contenu du post avant le formulaire
#   'after' : Affiche le contenu du post après le formulaire
#   'hide' : Masque le contenu du post
#   'only' : Affiche seulement le contenu du post, le formulaire est masqué et doit être appelé manuellement
#   false : Masque à la fois le contenu du post et le formulaire
content_display:    'before'

# @var array $form Attributs de configuration du formulaire
# @see \tiFy\Core\Forms\Forms::register()
form:
  title:            "<?php _e( 'Formulaire de contact', 'tify' );?>"

  container_class:  'tiFySetContactForm'

  fields:
    -
      slug:         'lastname'
      label:        "<?php _e( 'Nom', 'tify' );?>"
      placeholder:  "<?php _e( 'Renseignez votre nom', 'tify' );?>"
      type:         'input'
      required:     true
    -
      slug:         'firstname'
      label:        "<?php _e( 'Prénom', 'tify' );?>"
      placeholder:  "<?php _e( 'Renseignez votre prénom', 'tify' );?>"
      type:         'input'
      required:     true
    -
      slug:         'email'
      label:        "<?php _e( 'Adresse mail', 'tify' );?>"
      placeholder:  "<?php _e( 'Indiquez votre adresse email', 'tify' );?>"
      type:         'input'
      integrity_cb: 'is_email'
      required:     true
    -
      slug:         'subject'
      label:        "<?php _e( 'Sujet du message', 'tify' );?>"
      placeholder:  "<?php _e( 'Sujet de votre message', 'tify' );?>"
      type:         'input'
      required:     true
    -
      slug:         'message'
      label:        "<?php _e( 'Message', 'tify' );?>"
      placeholder:  "<?php _e( 'Votre message', 'tify' );?>"
      type:         'textarea'
      required:     true
    -
      slug:         'captcha'
      label:        "<?php _e( 'Code de sécurité', 'tify' );?>"
      placeholder:  "<?php _e( 'Code de sécurité', 'tify' );?>"
      type:         'simple-captcha-image'

  addons:
    mailer:         true

# @param array $router {
#     Attributs de configuration de la page d'affichage du formulaire
#
#     @param string $title Intitulé de qualification de la route
#     @param string $desc Texte de description de la route
#     @param string object_type Type d'objet (post|taxonomy) en relation avec la route
#     @param string object_name Nom de qualification de l'objet en relation (ex: post, page, category, tag ...)
#     @param string option_name Clé d'index d'enregistrement en base de données
#     @param int selected Id de l'objet en relation
#     @param string list_order Ordre d'affichage de la liste de selection de l'interface d'administration
#     @param string show_option_none Intitulé de la liste de selection de l'interface d'administration lorsqu'aucune relation n'a été établie
# }
router:              true
