# Environnement de surcharge
app:
  namespace:          'App'
  base_dir:           '<?php echo get_template_directory() ."/app";?>'
  bootstrap:          'Autoload'

# Déclaration des jeux de fonctionnalités personnalisés
set:

# @todo Liste des utilisateurs habilités
allowed_users:      []