login_redirect:
  enabled:        false
  
  endpoints:
    login:         'tiFy_login'  
    logout:        'tiFy_logout'
    resetpass:     'tiFy_resetpass'
    lostpassword:  'tiFy_lostpassword'
    register:      'tiFy_register'
    postpass:      'tiFy_postpass'