# Theme
theme:            'dark'
# Couleur de fond
overlay:          true
# Indicateur de chargement 
spinner:          true
# Bouton de fermeture
close_button:     true
# Légende (basé sur le alt de l'image)
caption:          true
# Flèche de navigation suivant/précédent 
navigation:       true
# Onglets de navigation  
tabs:             true
# Activation de la navigation au clavier
keyboard:         true
# Fermeture au clic sur le fond
overlay_close:    false
# Vitesse d'animation des images
animation_speed:  250
# Liste des contextes d'execution
context:          ['gallery','article']