defaults:
  # Type de post du recherche
  post_type:          'any'
  
  # Nombre d'éléments affichés par section
  posts_per_section:  4  
  
  # Champs de recherche principaux
  fields:             ['post_title','post_excerpt','post_content']
  
sections:
  # Exemple :  
  ## Identification de la section
  # identifiant-de-test:
    ## type de post de la section dans la page de résultat de recherche
    # post_type:      'page'
    
    ## Champs de recherche
    # fields:         ['post_title','post_content'] 

    ## Champs de recherche par clef de métadonnée
    # postmeta:       ['data', '_reference']  
    
    ## Activation de la recherche par mots-clefs
    # tags:           true