# Modification de la requête globale de Wordpress
#global:
  # Liste des champs utilisés pour la recherche
  # @var string[]
  #search_fields:      ['post_title', 'post_excerpt', 'post_content']

  # Liste de métadonnées utilisées pour la recherche
  # @var string[]
  #search_metas:       []

  # Activation de la recherche par mots-clef
  # @var bool
  #search_tags:        false

  # Activation de la recherche de la séquence complète ou sur chacun des mots constituant la séquences
  # @var bool
  #sentence:           true

  # Activation de la recherche selon le (les) terme(s) exact(s) de la séquence
  # @var bool
  #exact:              false

  # Arguments de requête Wordpress
  # @see https://codex.wordpress.org/Class_Reference/WP_Query
  # Limite la recherche à un ou plusieurs types de post
  # post_type:        ['page', 'post]
  #
  # Limiter le nombre de post par page dans les resultats de recherche
  # posts_per_page:   20
  # ...

# Liste des types de posts pour lesquels les mots clefs de recherche sont actifs. Peut être une chaîne de caractères séparées par des virgules.
# @var string|array
search_tags_post_types:  []
