# @var string $pos Position de l'interface left (default)|right.
pos:                'left'

# @var string $initial Etat initial de l'interface closed (default)|opened.
initial:            'closed'

# @var string|int $width Largeur de l'interface en px ou en %. Si l'unité de valeur n'est pas renseignée l'unité par défault est le px.
width:              '300px'

# @var int $z-index Profondeur de champs.
z-index:            99990

# @var string|int $min-width Largeur de la fenêtre du navigateur en px ou %, à partir de laquelle l'interface est active. Si l'unité de valeur n'est pas renseignée l'unité par défault est le px.
min-width:          '991px'

# @var bool $animated Activation de l'animation à l'ouverture et la fermeture
animated:           true

# @var bool|string $toggle Activation et contenu de bouton de bascule. Si la valeur booléene active ou desactive le bouton; la valeur chaîne de caractère active et affiche la chaîne ex : <span>X</span>
toggle:             true

# @var bool $enqueue_scripts Mise en file automatique des scripts (dans tous les contextes)
enqueue_scripts:    true

# @var array[] {
#   Liste des greffons (node) Elements de menu
#   @var string $id Identifiant du greffon
#   @var string $class Classe HTML du greffon
#   @var string $content Contenu du greffon
#   @var int $position Position du greffon
#   @todo \tiFy\Lib\Nodes\Base ne gère pas encore la position
# }
nodes:              []