# Paramètres généraux des emails
global:
  ## Destinataires
  #to:
  ## Expéditeur (unique)
  #from:
  ## Destinataire de réponse
  #reply_to:
  ## Copie carbone
  #cc:
  ## Copie cachée
  #bcc:
  ## Sujet
  #subject:
  ## Message
  #message:
  ## Entête de message
  #message_header:
  ## Pied de page de message
  #message_footer:
  ## Mode debug
  #debug:          false

# Paramètres des emails système de Wordpress
wp:
  # Changement de mot de passe
  password_change :
    
  # Changement d'adresse mail
  email_change :
  
  # Récupération de mot de passe
  retrieve_password :

# Déclaration d'emails personnalisés et de leurs paramètres
custom: